export const TasksData = [
  {
    id: 1,
    title: "User experience desing",
    description: "Designing the user experience of the application",
    status: "In Progress",
    progress_percentage: 50,
    priority: 1,
    assignee: "John Doe",
    created_by: "John Doe",
    created_at: "2020-01-01",
    updated_at: "2020-01-01",
  },
  {
    id: 2,
    title: "Meeting with the client",
    description: "Designing the user experience of the application",
    status: "In Progress",
    progress_percentage: 75,
    priority: 2,
    assignee: "John Doe",
    created_by: "John Doe",
    created_at: "2020-01-01",
    updated_at: "2020-01-01",
  },
  {
    id: 3,
    title: "User experience desing",
    description: "Designing the user experience of the application",
    status: "Completed",
    progress_percentage: 100,
    priority: 3,
    assignee: "John Doe",
    created_by: "John Doe",
    created_at: "2020-01-01",
    updated_at: "2020-01-01",
  },
  {
    id: 4,
    title: "User experience desing",
    description: "Designing the user experience of the application",
    status: "Completed",
    progress_percentage: 100,
    priority: 3,
    assignee: "John Doe",
    created_by: "John Doe",
    created_at: "2020-01-01",
    updated_at: "2020-01-01",
  },
  {
    id: 5,
    title: "User experience desing",
    description: "Designing the user experience of the application",
    status: "Completed",
    progress_percentage: 100,
    priority: 3,
    assignee: "John Doe",
    created_by: "John Doe",
    created_at: "2020-01-01",
    updated_at: "2020-01-01",
  },
  {
    id: 6,
    title: "User experience desing",
    description: "Designing the user experience of the application",
    status: "Completed",
    progress_percentage: 100,
    priority: 3,
    assignee: "John Doe",
    created_by: "John Doe",
    created_at: "2020-01-01",
    updated_at: "2020-01-01",
  },
];
