export const Tasks = [
	{
		taskTitle: 'Task 1',
		taskDescription: 'Task 1 Description',
		taskStatus: 'New',
		taskPriority: 'Low',
		taskDueDate: '2020-01-01',
		taskAssignees: 'User 1',
		taskId: '1',
	},
	{
		taskTitle: 'Task 2',
		taskDescription: 'Task 2 Description',
		taskStatus: 'New',
		taskPriority: 'Medium',
		taskDueDate: '2020-02-02',
		taskAssignees: 'User 2',
		taskId: '2',
	},
	{
		taskTitle: 'Task 3',
		taskDescription: 'Task 3 Description',
		taskStatus: 'New',
		taskPriority: 'High',
		taskDueDate: '2020-03-03',
		taskAssignees: 'User 3',
		taskId: '3',
	},
	// {
	// 	taskTitle: 'Task 4',
	// 	taskDescription: 'Task 4 Description',
	// 	taskStatus: 'New',
	// 	taskPriority: 'Low',
	// 	taskDueDate: '2020-04-04',
	// 	taskAssignees: 'User 4',
	// 	taskId: '4',
	// },
	// {
	// 	taskTitle: 'Task 5',
	// 	taskDescription: 'Task 5 Description',
	// 	taskStatus: 'New',
	// 	taskPriority: 'Low',
	// 	taskDueDate: '2020-05-05',
	// 	taskAssignees: 'User 5',
	// 	taskId: '5',
	// },
	// {
	// 	taskTitle: 'Task 6',
	// 	taskDescription: 'Task 6 Description',
	// 	taskStatus: 'New',
	// 	taskPriority: 'Low',
	// 	taskDueDate: '2020-06-06',
	// 	taskAssignees: 'User 6',
	// 	taskId: '6',
	// },
	// {
	// 	taskTitle: 'Task 7',
	// 	taskDescription: 'Task 7 Description',
	// 	taskStatus: 'New',
	// 	taskPriority: 'Low',
	// 	taskDueDate: '2020-07-07',
	// 	taskAssignees: 'User 7',
	// 	taskId: '7',
	// },
	// {
	// 	taskTitle: 'Task 8',
	// 	taskDescription: 'Task 8 Description',
	// 	taskStatus: 'New',
	// 	taskPriority: 'Low',
	// 	taskDueDate: '2020-08-08',
	// 	taskAssignees: 'User 8',
	// 	taskId: '8',
	// },
	// {
	// 	taskTitle: 'Task 9',
	// 	taskDescription: 'Task 9 Description',
	// 	taskStatus: 'New',
	// 	taskPriority: 'Low',
	// 	taskDueDate: '2020-09-09',
	// 	taskAssignees: 'User 9',
	// 	taskId: '9',
	// },
	// {
	// 	taskTitle: 'Task 10',
	// 	taskDescription: 'Task 10 Description',
	// 	taskStatus: 'New',
	// 	taskPriority: 'Low',
	// 	taskDueDate: '2020-10-10',
	// 	taskAssignees: 'User 10',
	// 	taskId: '10',
	// },
]
